spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mindfire
    url: jdbc:mysql://localhost:3306/practicedb
    username: onboard
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
